### ISSUE TITLE
Modem + TD-MPC2

### ISSUE THREAD

**Issue by dirkmcpherson** [facebookresearch/modem#6]
It looks like this exact algorithm is applicable to TD-MPC2, would you agree with that? Do you have an implementation based off of your TD-MPC2 repo?

Thanks for publishing!

**Comment by nicklashansen** [comment]
Yes! Integrating the improvements in TD-MPC2 into MoDem is possible and I would expect it to improve results. It's in the pipeline but we don't have a released version of that at the moment.
